SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimit 22020096
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml application/json
SecResponseBodyLimit 1048576
SecResponseBodyLimitAction ProcessPartial
SecTmpDir /tmp
SecDataDir /tmp
SecAuditEngine RelevantOnly
SecAuditLogFormat JSON
SecAuditLogType Serial
# Do not log request/response bodies or headers with credentials.
SecAuditLogParts AHZ
SecAuditLog /var/log/apache2/modsec_audit.log
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecRule REQUEST_HEADERS:Content-Type "application/json" "id:200001,phase:1,pass,nolog,t:lowercase,ctl:requestBodyProcessor=JSON"
Include /opt/owasp-crs/crs-setup.conf
Include /policies/waf.conf
Include /opt/owasp-crs/rules/*.conf
