Listen 8080
ServerTokens Prod
ServerSignature Off
Include /etc/modsecurity/kt88.conf
<VirtualHost *:8080>
  ProxyPreserveHost On
  ProxyAddHeaders Off
  RemoteIPHeader X-Forwarded-For
  RemoteIPTrustedProxy 10.88.33.80
  RequestHeader set X-Forwarded-For expr=%{REMOTE_ADDR}
  RequestHeader set X-Forwarded-Proto "https"
  ProxyPass / http://control:8000/ connectiontimeout=5 timeout=90
  ProxyPassReverse / http://control:8000/
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  LimitRequestBody 22020096
  ErrorLog /var/log/apache2/error.log
  CustomLog /var/log/apache2/access.log "%a %t %m %U %>s %D"
</VirtualHost>
